---
title: "Learning"

---

## Conferences and Workshops Attended

*   **NSF-CBMS Conference on Additive Combinatorics**
    University of South Carolina, Columbia, SC. May 2018

*   **Georgia Discrete Analysis Conference**
    University of Georgia, Athens, GA. May 2018
    
*   **International Workshop on Graph Limits**
    École Normale Supérieure de Lyon, Lyon, France. Spring 2018

*   **International Research School on Graph Limits**
    École Normale Supérieure de Lyon, Lyon, France. January 2018
    
*   **Graduate Research Workshop in Combinatorics**
    University of Colorado Denver & University of Denver, Denver, CO. July 2017

*   **4th Lake Michigan Workshop on Combinatorics**
    Western Michigan University, Kalamazoo, MI. April 2017

*   **Joint Mathematics Meeting**
    Washington State Convention Center, Seattle, WA. January 2016

*   **Young Mathematics Conference**
    Ohio State University, Columbus, OH. August 2015
    
*   **South Carolian Junior Academy of Science Annual Meeting**
    University of South Carolina Aiken, Aiken, SC. February 2012




